Metrics/LineLength:
  Max: 96

Style/Documentation:
  Exclude:
    - '**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/ssource.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
